### ISSUE TITLE
DllImport fails to find numerous libraries with Android builds (xenko 1.6.4-beta)

### ISSUE THREAD

**Issue by bpdavis2006** [SiliconStudio/xenko#400] opened 2016-05-08 21:12 UTC
Running the Space Escape example program after successfully building and deploying it to my Android devices resulted in immediate crashes.  The debug log ends with a System.NotSupportedException being thrown.

I tried installing version xenko 1.5.4-beta and built and deployed its Space Escape example.  It had no errors or crashes.

I realize that the 1.6.4 version has a new engine.  Perhaps something was omitted from the installation?  I'm providing my debug log file [AndroidOutputXenko_1.6.4.txt](https://github.com/SiliconStudio/xenko/files/254113/AndroidOutputXenko_1.6.4.txt) in the hope that it will help.

**Comment by sinkingsugar** [comment] 2016-05-09 00:13
Hi, thanks for be report! Could you try another sample? Also I assume that you did not change anything in the project configuration? 

Please let us know which Xamarin version you are using also.

**Comment by bpdavis2006** [comment] 2016-05-09 03:13
I tried running a number of the examples, but the only one that I had any success with was an unmodified "New Game", and I was able to get it to run on only one of my Android devices.  Unfortunately, while it did run, it did not look correct.  For instance, the center point of the sphere that reflects the light was red.  The shadows were also incorrect and did not match the windows version at all.  Prior to starting, the entire scene flashed a bright white, and then the scene settled in to what I tried to just describe.  I will attempt to record a video and attach it to my email response that I received from the system earlier.

The examples that did not work are: Jumpy Jet, SpaceEscape, Animated Model sample, and Game Menu UI Sample.  These all ended with the "Unfortunately, ____ has stopped." message.

Here are the Xamarin versions (according to Help about in VS 2015 Community Update 2)

Xamarin 4.0.3.214 (0dd817c)
Xamarin.Android 6.0.3.5 (a94a03b)
Xamarin.iOS 9.6.1.8 (3a25bf1)

**Comment by bpdavis2006** [comment] 2016-05-09 03:42
Here are the images of the application running on my tablet.  Also, the zip file contains a 4 second clip.

[video.zip](https://github.com/SiliconStudio/xenko/files/254283/video.zip)
![img_20160508_222249054](https://cloud.githubusercontent.com/assets/19231717/15103145/0a5801c6-1565-11e6-9e5e-038abb716362.jpg)
![img_20160508_222248655](https://cloud.githubusercontent.com/assets/19231717/15103147/0a596dae-1565-11e6-9a7b-7346b0db3321.jpg)
![img_20160508_222248454](https://cloud.githubusercontent.com/assets/19231717/15103146/0a58b378-1565-11e6-8486-9af9fd7b7e43.jpg)

**Comment by sinkingsugar** [comment] 2016-05-09 03:47
I really have no way to reproduce any of those issues sadly. Could you try to switch from both Xamarin Studio and Visual Studio Xamarin options to the Xamarin Alpha channel release and try again to run all?
Also could you try to deploy a pure Xamarin Opengl ES template project to any of those devices?

**Comment by sinkingsugar** [comment] 2016-05-09 03:52
Also it seems that you are trying to AOT the assemblies when building for android, could you confirm me that you are not doing that? (not supported feature.. experimental even xamarin side)

**Comment by bpdavis2006** [comment] 2016-05-09 04:16
I'd be happy to try switching the options as requested, however I am not sure where to find the Camarillo Alpha channel release options. I'm assuming that the Visual Studio Xamarin options are located in the Tools-Option-Xamarin  dialog.

In regard to trying to AOT the assemblies... if I am, it is by pure ignorance that I have done so. :)  How can I confirm this for you? 

Could you send me a couple of screenshots for the above two items?

Finally, I tested a Xamarin Open gl ES application provided by one of their templates  (a simple spinning cube) and it execute fine.

**Comment by sinkingsugar** [comment] 2016-05-09 06:25
By default it should not AOT, so you should be fine! As long as you don't change any options manually we should be on the same page.
It is still very strange tho... are you building in debug mode?

**Comment by bpdavis2006** [comment] 2016-05-09 07:18
I have tried both release and debug modes.  Both fail.

I'm attaching a debug output file that was captured using Xamarin in diagnostic mode.  Perhaps that might shed some light on this problem?
[Output-Debug.txt](https://github.com/SiliconStudio/xenko/files/254457/Output-Debug.txt)

**Comment by sinkingsugar** [comment] 2016-05-09 07:36
Could you please tell us the android device model names you are using? Looks like it is just an opengl es issue.

**Comment by xen2** [comment] 2016-05-09 07:36
It seems it can't create the main EGL context.

What is your Android device?

**Comment by bpdavis2006** [comment] 2016-05-09 15:15
I have two at the moment: a Samsung T320 (KitKat 4.4) and a Moto G 3rd gen (lollipop 5.1)

**Comment by bpdavis2006** [comment] 2016-05-09 15:20
Does my Xamarin versioning match yours? And if it is an opengl issue, is there an easy way to test other modes?

**Comment by xen2** [comment] 2016-05-27 02:41
I think this one is fixed by c8797fc78409af7850a3faa223d40fe1141fd38e
We'll likely release 1.6.6 with it today.

**Comment by xen2** [comment] 2016-06-21 09:11
Closing, please let us know if it happens again with latest version.

**Closed by xen2** 2016-06-21 09:11 UTC
Labels: bug
