### ISSUE TITLE
Game Studio "crashes" when saving project

### ISSUE THREAD

**Issue by SvenEV** [SiliconStudio/xenko#504] opened 2016-12-13 23:31 UTC
Whenever I create and edit a Xenko project (add/remove assets, edit scenes/scripts, ...), the project over time eventually reaches a "state" in which saving the project (hitting the Save button) makes Game Studio "crash" every time. However, according to the Task Manager, Game Studio is still running, so it seems to only be a UI issue. In fact, if the project got saved as a consequence of pressing F5, the game will correctly compile in the background and start up, without Game Studio being visible.

The problem never occurs in new projects, but occurs almost every time in "affected projects". That is, if I close the invisible Game Studio via Task Manager, reopen the affected project and press the Save button again (even without changing anything), the Game Studio window closes again in most cases.

I will try to prepare a project for reproduction. Please let me know if there is any other information (log files etc.) I could share.

My configuration: Surface Pro 3 @ 150% DPI scaling, Windows 10 Build 14393, Xenko 1.9.2-beta (issue also applies to older versions like 1.8-beta)

**Comment by jason-wilmans** [comment] 2016-12-20 21:29
I think I'm experiencing a similar issue. Except it can be caused by more triggers than trying to save. For example the "Reload Assets" button is a surefire way to get the studio to hang.

**Comment by EternalTamago** [comment] 2016-12-21 02:08
Hello.
When I saved some projects I encountered a similar problem that the Game Studio disappered from the screen and did not come back.
In my case, I could avoid the problem by stopping the Touch Keyboard and Handwriting Panel Service.

**Comment by xen2** [comment] 2016-12-21 02:26
That seems quite an important issue that several people encounter.

We will try to find the cause on our side, but if anybody happen to find repro steps, it would help to fix it faster!

**Comment by EternalTamago** [comment] 2016-12-22 07:59
It occurs with the following steps.

1. Create New Game project with the Particles Pack.
2. Move the sphere from (0, 0.5, 0) to (0, 0.5, 1).(X,Y,Z)
3. Save the project.

Xenko 1.9.2-beta/Launcher v1.53
Visual Studio Community 2015 Update3 
Windows10 Pro x64

**Comment by SvenEV** [comment] 2016-12-22 10:18
@EternalTamago  I can confirm that the issue can be reproduced with these steps (even without the Particles Pack).

**Comment by SvenEV** [comment] 2017-02-13 23:32
Just wanted to let you know that the workaround no longer works for me. I frequently experience the issue again, mostly when saving projects or importing assets.

**Comment by Benlitz** [comment] 2017-02-14 09:12
Hi,

This issue seems to affect more and more people, we'll try to fix it as soon as possible.
Meanwhile, can you try to unplug your drawing tablet if you have one, and let us know if it still happens?

**Comment by SvenEV** [comment] 2017-02-14 11:06
I'm using a Surface Pro 3 so there is nothing to unplug (apart from the keyboard). But I can try to disable certain devices in Device Manager and see what happens.

**Comment by Benlitz** [comment] 2017-03-17 06:40
We modified the way we handle modal windows and it seems to have fixed this issue. The fix will be in the next release.

**Closed by Benlitz** 2017-03-17 06:40 UTC
Labels: bug
