### ISSUE TITLE
[Bug 1.5.1] Skybox of default game failes to compile

### ISSUE THREAD

**Issue by LennyPenny** [SiliconStudio/xenko#344] opened 2016-01-05 22:56 UTC
I'm getting this error when trying to compile a freshly created game on 1.5.1

```
[]: Error: Exception in command 3207eda6-0e99-487a-9018-978f7192c883: SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateBuffer(BufferDescription& descRef, Nullable`1 initialDataRef, Buffer bufferOut)
   at SharpDX.Direct3D11.Buffer..ctor(Device device, IntPtr dataPointer, BufferDescription description)
   at SiliconStudio.Xenko.Graphics.Buffer.InitializeFromImpl(BufferDescription description, BufferFlags viewFlags, PixelFormat viewFormat, IntPtr dataPointer) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Graphics\Direct3D\Buffer.Direct3D.cs:line 48
   at SiliconStudio.Xenko.Graphics.Buffer.New(GraphicsDevice device, BufferDescription description, PixelFormat viewFormat) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Graphics\Buffer.cs:line 394
   at SiliconStudio.Xenko.Graphics.GraphicsResourceAllocator.CreateBuffer(BufferDescription description, PixelFormat viewFormat) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Graphics\GraphicsResourceAllocator.cs:line 167
   at SiliconStudio.Xenko.Graphics.GraphicsResourceAllocator.GetTemporaryResource[TResource,TKey](Dictionary`2 cache, TKey description, Func`3 creator, Func`2 getDefinition, PixelFormat viewFormat) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Graphics\GraphicsResourceAllocator.cs:line 233
   at SiliconStudio.Xenko.Graphics.GraphicsResourceAllocator.GetTemporaryBuffer(BufferDescription description, PixelFormat viewFormat) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Graphics\GraphicsResourceAllocator.cs:line 118
   at SiliconStudio.Xenko.Rendering.RendererCoreBase.NewScopedBuffer(BufferDescription description, PixelFormat viewFormat) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Engine\Rendering\RendererCoreBase.cs:line 154
   at SiliconStudio.Xenko.Rendering.RendererCoreBase.NewScopedTypedBuffer(Int32 count, PixelFormat viewFormat, Boolean isUnorderedAccess, GraphicsResourceUsage usage) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Engine\Rendering\RendererCoreBase.cs:line 163
   at SiliconStudio.Xenko.Rendering.ComputeEffect.LambertianPrefiltering.LambertianPrefilteringSH.DrawCore(RenderContext context) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Engine\Rendering\ComputeEffect\LambertianPrefiltering\LambertianPrefilteringSH.cs:line 77
   at SiliconStudio.Xenko.Rendering.RendererBase.Draw(RenderContext context) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Engine\Rendering\RendererBase.cs:line 48
   at SiliconStudio.Xenko.Rendering.DrawEffect.Draw(RenderContext context, String name) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Engine\Rendering\DrawEffect.cs:line 101
   at SiliconStudio.Xenko.Rendering.DrawEffect.Draw(String name) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Engine\Rendering\DrawEffect.cs:line 110
   at SiliconStudio.Xenko.Assets.Skyboxes.SkyboxGenerator.Compile(SkyboxAsset asset, SkyboxGeneratorContext context) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Assets\Skyboxes\SkyboxGenerator.cs:line 101
   at SiliconStudio.Xenko.Assets.Skyboxes.SkyboxAssetCompiler.SkyboxCompileCommand.DoCommandOverride(ICommandContext commandContext) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Assets\Skyboxes\SkyboxAssetCompiler.cs:line 93
   at SiliconStudio.BuildEngine.Command.DoCommand(ICommandContext commandContext) in C:\TeamCity\work\e6f0ed62352ac70f\sources\common\buildengine\SiliconStudio.BuildEngine.Common\Command.cs:line 80
   at SiliconStudio.BuildEngine.CommandBuildStep.<StartCommand>d__21.MoveNext() in C:\TeamCity\work\e6f0ed62352ac70f\sources\common\buildengine\SiliconStudio.BuildEngine.Common\CommandBuildStep.cs:line 446
[C:/Users/Lenny/Documents/Xenko Projects/Hover/Hover/Assets/Shared/Skybox.xksky(1,1)]: Error: BuildStep 3207eda6-0e99-487a-9018-978f7192c883 failed.
[]: Error: Exception in command 3207eda6-0e99-487a-9018-978f7192c883: SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateBuffer(BufferDescription& descRef, Nullable`1 initialDataRef, Buffer bufferOut)
   at SharpDX.Direct3D11.Buffer..ctor(Device device, IntPtr dataPointer, BufferDescription description)
   at SiliconStudio.Xenko.Graphics.Buffer.InitializeFromImpl(BufferDescription description, BufferFlags viewFlags, PixelFormat viewFormat, IntPtr dataPointer) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Graphics\Direct3D\Buffer.Direct3D.cs:line 48
   at SiliconStudio.Xenko.Graphics.Buffer.New(GraphicsDevice device, BufferDescription description, PixelFormat viewFormat) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Graphics\Buffer.cs:line 394
   at SiliconStudio.Xenko.Graphics.GraphicsResourceAllocator.CreateBuffer(BufferDescription description, PixelFormat viewFormat) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Graphics\GraphicsResourceAllocator.cs:line 167
   at SiliconStudio.Xenko.Graphics.GraphicsResourceAllocator.GetTemporaryResource[TResource,TKey](Dictionary`2 cache, TKey description, Func`3 creator, Func`2 getDefinition, PixelFormat viewFormat) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Graphics\GraphicsResourceAllocator.cs:line 233
   at SiliconStudio.Xenko.Graphics.GraphicsResourceAllocator.GetTemporaryBuffer(BufferDescription description, PixelFormat viewFormat) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Graphics\GraphicsResourceAllocator.cs:line 118
   at SiliconStudio.Xenko.Rendering.RendererCoreBase.NewScopedBuffer(BufferDescription description, PixelFormat viewFormat) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Engine\Rendering\RendererCoreBase.cs:line 154
   at SiliconStudio.Xenko.Rendering.RendererCoreBase.NewScopedTypedBuffer(Int32 count, PixelFormat viewFormat, Boolean isUnorderedAccess, GraphicsResourceUsage usage) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Engine\Rendering\RendererCoreBase.cs:line 163
   at SiliconStudio.Xenko.Rendering.ComputeEffect.LambertianPrefiltering.LambertianPrefilteringSH.DrawCore(RenderContext context) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Engine\Rendering\ComputeEffect\LambertianPrefiltering\LambertianPrefilteringSH.cs:line 77
   at SiliconStudio.Xenko.Rendering.RendererBase.Draw(RenderContext context) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Engine\Rendering\RendererBase.cs:line 48
   at SiliconStudio.Xenko.Rendering.DrawEffect.Draw(RenderContext context, String name) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Engine\Rendering\DrawEffect.cs:line 101
   at SiliconStudio.Xenko.Rendering.DrawEffect.Draw(String name) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Engine\Rendering\DrawEffect.cs:line 110
   at SiliconStudio.Xenko.Assets.Skyboxes.SkyboxGenerator.Compile(SkyboxAsset asset, SkyboxGeneratorContext context) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Assets\Skyboxes\SkyboxGenerator.cs:line 101
   at SiliconStudio.Xenko.Assets.Skyboxes.SkyboxAssetCompiler.SkyboxCompileCommand.DoCommandOverride(ICommandContext commandContext) in C:\TeamCity\work\e6f0ed62352ac70f\sources\engine\SiliconStudio.Xenko.Assets\Skyboxes\SkyboxAssetCompiler.cs:line 93
   at SiliconStudio.BuildEngine.Command.DoCommand(ICommandContext commandContext) in C:\TeamCity\work\e6f0ed62352ac70f\sources\common\buildengine\SiliconStudio.BuildEngine.Common\Command.cs:line 80
   at SiliconStudio.BuildEngine.CommandBuildStep.<StartCommand>d__21.MoveNext() in C:\TeamCity\work\e6f0ed62352ac70f\sources\common\buildengine\SiliconStudio.BuildEngine.Common\CommandBuildStep.cs:line 446
[]: Error: Asset [Skybox] failed to compile
[C:/Users/Lenny/Documents/Xenko Projects/Hover/Hover/Assets/Shared/Skybox.xksky(1,1)]: Error: BuildStep Asset build steps [SkyboxAsset:'Skybox'] (1 items) failed.
[]: Error: Asset [Skybox] failed to compile
[C:/Users/Lenny/Documents/Xenko Projects/Hover/Hover/Assets/Shared/Skybox.xksky(1,1)]: Error: BuildStep Build step list (2 items) failed.
[]: Error: BuildStep Build step list (289 items) failed.
[]: Error: BuildStep Build step list (1 items) failed.
[]: Error: Build finished in 577 steps. Command results: 4 succeeded, 568 up-to-date, 5 failed, 0 not triggered due to previous failure.
[]: Error: Build failed.
```

**Comment by xenux** [comment] 2016-01-06 00:52
Hi, thank you for the report.
It looks like a duplicate of #266.
This task seems an issue for a lot of people though.
We will try to fix it very soon.

**Comment by jwollen** [comment] 2016-01-15 05:31
We just releases version 1.5.2 which should fix most Skybox-issues. Let us know if it works for you, if you have time to test it.

**Closed** 2016-01-18 01:29 UTC
Labels: bug, duplicate
