### ISSUE TITLE
SimpleTerrain Error: NullReferenceException [v1.3.4]

### ISSUE THREAD

**Issue by HarkBack** [SiliconStudio/xenko#317] opened 2015-10-08 08:57 UTC
HiI. I have created an example 'SimpleTerrain' and immediately after the launch was a error.
```
{[SceneInstance]: Error: An exception occurred while rendering. System.NullReferenceException.
   in SiliconStudio.Paradox.Rendering.UIComponentRenderer.PrepareCore(RenderContext context, RenderItemCollection opaqueList, RenderItemCollection transparentList)
   in SiliconStudio.Paradox.Rendering.EntityComponentRendererBase.Prepare(RenderContext context, RenderItemCollection opaqueList, RenderItemCollection transparentList)
   in SiliconStudio.Paradox.Rendering.EntityComponentRendererBatch.DrawRenderer(RenderContext context, IEntityComponentRenderer renderer)
   in SiliconStudio.Paradox.Rendering.GraphicsRendererCollectionBase`1.DrawCore(RenderContext context)
   in SiliconStudio.Paradox.Rendering.EntityComponentRendererBatch.DrawCore(RenderContext context)
   in SiliconStudio.Paradox.Rendering.RendererBase.Draw(RenderContext context)
   in SiliconStudio.Paradox.Rendering.CameraRendererMode.DrawCore(RenderContext context)
   in SiliconStudio.Paradox.Rendering.CameraRendererModeForward.DrawCore(RenderContext context)
   in SiliconStudio.Paradox.Rendering.RendererBase.Draw(RenderContext context)
   in SiliconStudio.Paradox.Rendering.SceneCameraRenderer.DrawCore(RenderContext context, RenderFrame output)
   in SiliconStudio.Paradox.Rendering.SceneRendererBase.DrawCore(RenderContext context)
   in SiliconStudio.Paradox.Rendering.RendererBase.Draw(RenderContext context)
   in SiliconStudio.Paradox.Rendering.GraphicsRendererCollection`1.DrawRenderer(RenderContext context, T renderer)
   in SiliconStudio.Paradox.Rendering.GraphicsRendererCollectionBase`1.DrawCore(RenderContext context)
   in SiliconStudio.Paradox.Rendering.RendererBase.Draw(RenderContext context)
   in SiliconStudio.Paradox.Rendering.Composers.SceneGraphicsLayer.DrawCore(RenderContext context)
   in SiliconStudio.Paradox.Rendering.RendererBase.Draw(RenderContext context)
   in SiliconStudio.Paradox.Rendering.Composers.SceneGraphicsCompositorLayers.DrawCore(RenderContext context)
   in SiliconStudio.Paradox.Rendering.RendererBase.Draw(RenderContext context)
   in SiliconStudio.Paradox.Engine.SceneInstance.Draw(RenderContext context, RenderFrame toFrame, ISceneGraphicsCompositor compositorOverride)}
```
I note that in previous versions worked.
OS: Windows 7 x64 Pro SP1

**Comment by jwollen** [comment] 2015-10-13 01:52
Thanks for the report!

This was due to a regression in the entity system. It has been fixed on master and will be part of the next release.

**Comment by dfkeenan** [comment] 2015-10-24 12:23
Was the problem in the engine or the sample?  Can I fix the sample myself?

**Comment by jwollen** [comment] 2015-10-26 01:35
I was engine side, sadly. You can work around it for this sample, by removing the `UIComponent` from the UI entity in the editor (or in code, [before it is readded](https://github.com/SiliconStudio/paradox-samples/blob/3bcc31dab3e2754a37f8e52f1888b765413eb524/Graphics/SimpleTerrain/SimpleTerrain.Game/TerrainScript.cs#L457)).

**Comment by dfkeenan** [comment] 2015-10-26 01:49
Ok.  I had already commented out the UI code from the script and got it to run. Thanks for the response.

**Closed** 2015-12-18 01:58 UTC
Labels: bug, fixed
