### ISSUE TITLE
Most samples are broken

### ISSUE THREAD

**Issue by RecursiveCall** [SiliconStudio/xenko#354] opened 2016-02-21 06:23 UTC
As of 1.5.3 or possibly before then, most "New Projects" do not run and spit this out in the console:

```
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Could not compile shader. See error messages.[]: Error: C:/Program Files/Silicon Studio/Xenko/GamePackages/Xenko.1.5.3-beta/Assets/Shared/Materials/Shaders/MaterialSurfaceLightingAndShading.xksl(72,34): error X5608: Compiled shader code uses too many arithmetic instruction slots (108). Max. allowed by the target (ps_2_0) is 64. Consider increasing optimization level to reduce instruction count.
(1,1): error X5609: Compiled shader code uses too many instruction slots (110). Max. allowed by the target (ps_2_0) is 96.


   at SiliconStudio.Xenko.Rendering.EffectSystem.CheckResult(LoggerResult compilerResult) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\EffectSystem.cs:line 181
   at SiliconStudio.Xenko.Rendering.EffectSystem.CreateEffect(String effectName, EffectBytecodeCompilerResult effectBytecodeCompilerResult, CompilerResults compilerResult) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\EffectSystem.cs:line 205
   at SiliconStudio.Xenko.Rendering.EffectSystem.<>c__DisplayClass21_0.<LoadEffect>b__0(Task`1 x) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\EffectSystem.cs:line 166
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at SiliconStudio.Xenko.Rendering.DynamicEffectCompiler.CreateEffect(DynamicEffectInstance effectInstance, ParameterCollection passParameters) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\DynamicEffectCompiler.cs:line 219
   at SiliconStudio.Xenko.Rendering.DynamicEffectCompiler.Update(DynamicEffectInstance effectInstance, ParameterCollection passParameters) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\DynamicEffectCompiler.cs:line 159
   at SiliconStudio.Xenko.Rendering.ModelComponentRenderer.UpdateEffect(RenderContext context, RenderMesh renderMesh, ParameterCollection passParameters) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\ModelComponentRenderer.cs:line 378
   at SiliconStudio.Xenko.Rendering.ModelComponentRenderer.DrawCore(RenderContext context, RenderItemCollection renderItemList, Int32 fromIndex, Int32 toIndex) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\ModelComponentRenderer.cs:line 262
   at SiliconStudio.Xenko.Rendering.EntityComponentRendererBase.Draw(RenderContext context, RenderItemCollection renderItems, Int32 fromIndex, Int32 toIndex) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\EntityComponentRendererBase.cs:line 58
   at SiliconStudio.Xenko.Rendering.EntityComponentRendererBatch.Draw(RenderContext context, RenderItemCollection renderItems, IComparer`1 comparer) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\EntityComponentRendererBatch.cs:line 81
   at SiliconStudio.Xenko.Rendering.EntityComponentRendererBatch.DrawCore(RenderContext context) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\EntityComponentRendererBatch.cs:line 36
   at SiliconStudio.Xenko.Rendering.RendererBase.Draw(RenderContext context) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\RendererBase.cs:line 47
   at SiliconStudio.Xenko.Rendering.CameraRendererMode.DrawCore(RenderContext context) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\CameraRendererMode.cs:line 141
   at SiliconStudio.Xenko.Rendering.CameraRendererModeForward.DrawCore(RenderContext context) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\CameraRendererModeForward.cs:line 49
   at SiliconStudio.Xenko.Rendering.RendererBase.Draw(RenderContext context) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\RendererBase.cs:line 47
   at SiliconStudio.Xenko.Rendering.SceneCameraRenderer.DrawCore(RenderContext context, RenderFrame output) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\SceneCameraRenderer.cs:line 109
   at SiliconStudio.Xenko.Rendering.SceneRendererBase.DrawCore(RenderContext context) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\SceneRendererBase.cs:line 98
   at SiliconStudio.Xenko.Rendering.RendererBase.Draw(RenderContext context) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\RendererBase.cs:line 47
   at SiliconStudio.Xenko.Rendering.GraphicsRendererCollection`1.DrawRenderer(RenderContext context, T renderer) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\GraphicsRendererCollection.cs:line 19
   at SiliconStudio.Xenko.Rendering.GraphicsRendererCollectionBase`1.DrawCore(RenderContext context) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\GraphicsRendererCollectionBase.cs:line 173
   at SiliconStudio.Xenko.Rendering.RendererBase.Draw(RenderContext context) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\RendererBase.cs:line 47
   at SiliconStudio.Xenko.Rendering.Composers.SceneGraphicsLayer.DrawCore(RenderContext context) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\Composers\SceneGraphicsLayer.cs:line 135
   at SiliconStudio.Xenko.Rendering.RendererBase.Draw(RenderContext context) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\RendererBase.cs:line 47
   at SiliconStudio.Xenko.Rendering.GraphicsRendererCollection`1.DrawRenderer(RenderContext context, T renderer) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\GraphicsRendererCollection.cs:line 19
   at SiliconStudio.Xenko.Rendering.GraphicsRendererCollectionBase`1.DrawCore(RenderContext context) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\GraphicsRendererCollectionBase.cs:line 173
   at SiliconStudio.Xenko.Rendering.RendererBase.Draw(RenderContext context) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\RendererBase.cs:line 47
   at SiliconStudio.Xenko.Rendering.Composers.SceneGraphicsCompositorLayers.DrawCore(RenderContext context) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\Composers\SceneGraphicsCompositorLayers.cs:line 70
   at SiliconStudio.Xenko.Rendering.RendererBase.Draw(RenderContext context) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\RendererBase.cs:line 47
   at SiliconStudio.Xenko.Engine.SceneInstance.Draw(RenderContext context, RenderFrame toFrame, ISceneGraphicsCompositor compositorOverride) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Engine\SceneInstance.cs:line 161
---> (Inner Exception #0) System.InvalidOperationException: Could not compile shader. See error messages.[]: Error: C:/Program Files/Silicon Studio/Xenko/GamePackages/Xenko.1.5.3-beta/Assets/Shared/Materials/Shaders/MaterialSurfaceLightingAndShading.xksl(72,34): error X5608: Compiled shader code uses too many arithmetic instruction slots (108). Max. allowed by the target (ps_2_0) is 64. Consider increasing optimization level to reduce instruction count.
(1,1): error X5609: Compiled shader code uses too many instruction slots (110). Max. allowed by the target (ps_2_0) is 96.


   at SiliconStudio.Xenko.Rendering.EffectSystem.CheckResult(LoggerResult compilerResult) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\EffectSystem.cs:line 181
   at SiliconStudio.Xenko.Rendering.EffectSystem.CreateEffect(String effectName, EffectBytecodeCompilerResult effectBytecodeCompilerResult, CompilerResults compilerResult) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\EffectSystem.cs:line 205
   at SiliconStudio.Xenko.Rendering.EffectSystem.<>c__DisplayClass21_0.<LoadEffect>b__0(Task`1 x) in C:\TeamCity\work\e71632f3cedbf5cf\sources\engine\SiliconStudio.Xenko.Engine\Rendering\EffectSystem.cs:line 166
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

**Comment by xenux** [comment] 2016-02-22 01:55
Thank you for the report.
Could let us know which graphic card and OS you are using?

**Comment by RecursiveCall** [comment] 2016-02-22 01:56
Windows 10 Pro.
Intel HD 4600 + GTX970M

**Comment by xoofx** [comment] 2016-02-22 02:47
Could you check before it crashes what kind of adapter the GraphicsDevice is picking (`GraphicsAdapter Adapter.Description`)?  The message is returned by the driver, so it looks like even if we are able to compile the shader in 9.1 profile, it could fail to instantiate it on some gfx cards/drivers.

As a workaround, you can switch to 9.3 (in GameSettings)

**Comment by RecursiveCall** [comment] 2016-02-22 03:07
It selects the Intel driver (Intel(R) HD Graphics 4600 from description).

Setting to 9.3 (just before game.Run()) doesn't resolve the issue.

**Comment by xoofx** [comment] 2016-02-22 04:17
Thanks, we will check this. We might have indeed a regression as in the past we were automatically switching Intel to 10.0 internally as all 9.x profiles were giving unexpected results.

**Comment by xoofx** [comment] 2016-02-22 08:03
> Setting to 9.3 (just before game.Run()) doesn't resolve the issue.

This will not work, as the GameSettings are overriding this at initialization time. You need to change it in the GameSettings instead.

**Comment by xoofx** [comment] 2016-02-23 00:14
There should be an hlsl file under `MyGame\Bin\Windows\log` Could you attach it on gist? We would like to verify that it actually gives this error when compiling on non Intel machine.

**Comment by xoofx** [comment] 2016-02-23 01:36
Actually, we found the issue. This should be fixed on our dev branch and will be released soon. Thanks!

**Comment by RecursiveCall** [comment] 2016-02-23 07:35
Will validate and report back. Thank you.

**Closed** 2016-03-03 11:28 UTC
Labels: bug, fixed
