### ISSUE TITLE
Case issues with EditText

### ISSUE THREAD

**Issue by donnyv** [SiliconStudio/xenko#330] opened 2015-11-05 13:49 UTC
EditText enters everything as lowercase, even if caps lock is on.

**Comment by donnyv** [comment] 2015-11-06 02:07
Just noticed it doesn't accept decimal point either. Probably need to do a test with all secondary characters.

**Comment by xenux** [comment] 2015-11-06 02:21
Ok thanks :)

**Comment by stephanbe** [comment] 2016-03-18 20:31
We reproduced the bug, see [here](http://answers.xenko.com/questions/1795/edittext-ignores-non-alphanumeric-characters.html#answer-1797)

**Comment by xen2** [comment] 2016-03-26 04:20
Duplicate of #50, closing that one

**Closed by xen2** 2016-03-26 04:20 UTC
Labels: bug
