### ISSUE TITLE
Bug when building with Visual Studio 2015 Technical Preview

### ISSUE THREAD

**Issue by Borkason** [SiliconStudio/xenko#180] opened 2015-02-12 20:09 UTC
Okay, I know I am using an unsupported IDE. To make it worse, the IDE is also a technical preview version. I am not complaining! ;) Anyway, I'd like to mention, that as soon as you hit the Run/Debugging (F5) button, the project shows this build error:

> **Fehler** ""C:\Program Files (x86)\Paradox\GamePackages\Paradox.1.0.0-beta06\Bin\Windows-Direct3D11\SiliconStudio.AssemblyProcessor.exe" --platform=Windows --targetFramework=v4.5  --auto-notify-property --parameter-key --auto-module-initializer --serialization "D:\Documents\Paradox Projects\EasyGame\EasyGame\Bin\Windows-Direct3D11\Debug\EasyGame.Game.dll"" **wurde mit dem Code 1 beendet. EasyGame.Game**

Still, if you happen to have a fix, that would be nice. :smile:

**Edit:**

Alright, the break happens **only, when you rebuild the project using VS 2015 TP**. If you **simply run** the project using VS 2015 TP, the game will start without errors. If you make changes to the code and build or run the program using the Paradox3D windows, the game compiles and runs fine.

I used git to discover the changed files by VS 2015 TP that *might* cause the break:

    modified:   SpriteEntity.sln.ide/storage.ide
    modified:   SpriteEntity/Bin/Windows-Direct3D11/Debug/SpriteEntity.Game.dll
    modified:   SpriteEntity/Bin/Windows-Direct3D11/Debug/SpriteEntity.Game.pdb
    modified:   SpriteEntity/Bin/Windows-Direct3D11/Debug/SpriteEntity.exe
    modified:   SpriteEntity/Bin/Windows-Direct3D11/Debug/SpriteEntity.pdb
    modified:   SpriteEntity/SpriteEntity.Game/obj/Windows/Debug/SpriteEntity.Game.csprojResolveAssemblyReference.cache
    modified:   SpriteEntity/SpriteEntity.Game/obj/Windows/Debug/SpriteEntity.Game.dll
    modified:   SpriteEntity/SpriteEntity.Game/obj/Windows/Debug/SpriteEntity.Game.pdb
    modified:   SpriteEntity/SpriteEntity.Windows/obj/Windows/Debug/SpriteEntity.Windows.csprojResolveAssemblyReference.cache
    modified:   SpriteEntity/SpriteEntity.Windows/obj/Windows/Debug/SpriteEntity.exe
    modified:   SpriteEntity/SpriteEntity.Windows/obj/Windows/Debug/SpriteEntity.pdb

If I reset those files using `git checkout -- *` I can run the program again.

**Comment by boriscallens** [comment] 2015-02-20 13:30
The core error message is "Unknown custom metadata item kind: 6"
Where 6 can be any number higher then 4  
Although I'm not completely sure I understand everything correctly, I think it is the combination of VS2015's Roslyn compiler and the use of some kind of IL weaving (In Paradox's case this would be PostSharp) that brings a bug in Mono.Cecil to the surface.  
I think building the updated CCIMetadata from [here](https://ccimetadata.codeplex.com/SourceControl/latest#) and using it in the paradox build would solve this. Couldn't get the Paradox sln to build though and after a while I took the path of least resistance and used VS2013 instead ;)

The offending code is [here](https://github.com/mono/cecil/blob/3df0deadce4359275d7c813d40c067d021d1ed14/symbols/pdb/Microsoft.Cci.Pdb/PdbFunction.cs#L353-359), the issue is logged [here](https://roslyn.codeplex.com/workitem/54) and fixed [here](https://ccimetadata.codeplex.com/SourceControl/changeset/73073)

**Comment by xen2** [comment] 2015-02-22 06:29
I independently ran into the same issue a few days ago.

Latest Cecil fixed it, with this patch: https://github.com/jbevain/cecil/commit/d33d51499a0c19238f41db5a06ab01b1f7aae210

It will be included in next release.

**Closed** 2016-03-26 04:22 UTC
Labels: fixed
