### ISSUE TITLE
Cannot go to parent directory ".."

### ISSUE THREAD

**Issue by PantsStatusZero** [SiliconStudio/xenko#351] opened 2016-02-05 19:20 UTC
I had to load my project on a different computer and I am getting the below errors:

![capture](https://cloud.githubusercontent.com/assets/11089131/12856487/c5c0a37c-cc0a-11e5-91d0-24a6973fbbb6.JPG)

Project will not compile or open in Xenko Studio.

**Comment by Kryptos-FR** [comment] 2016-02-06 03:51
What was the directory structure before and how is it now?

**Comment by PantsStatusZero** [comment] 2016-02-06 04:11
Same and the same structure seem to work for other people on the project. I've tried deleting and re-pulling with no luck. The package is in the location it's looking for.

**Comment by xenux** [comment] 2016-02-08 03:48
Do you have any reference to files that are outside the _Yankee_ folder? 
Looks like it is trying to resolve something like this: "C:/Source/Yankee/" + "../../../../folder/folder/myasset.ext". Try to manually fix those references if any.

**Comment by jwollen** [comment] 2016-02-18 08:29
Hi!
We just published a bugfix release which should prevent this error.

The issue is most likely the one xenux described, though.
Could you try opening/building the project with the new version 1.5.3 and check if there are any build-error related to asset paths?

**Comment by PantsStatusZero** [comment] 2016-06-13 02:18
I don't have access the the project any more. But the issue end up being cause someone try to load terrain assets from one of the simple app's folder rather than importing the assets directly into the project.

**Comment by Benlitz** [comment] 2016-06-29 04:51
This issue should be fixed for good in 1.6.8. Please re-open or create a new issue if it happens again

**Closed by Benlitz** 2016-06-29 04:51 UTC
Labels: bug, fixed
