### ISSUE TITLE
SpriteFont asset with Signed Distant Field type throws OutOfMemoryException in the editor on certain fonts

### ISSUE THREAD

**Issue by EnoughTea** [SiliconStudio/xenko#515] opened 2017-01-23 21:33 UTC
Signed Distant Field SpriteFont asset throws OOM in the editor for certain fonts. At the same time, it works as expected for other fonts. It looks like exception occurs with fonts where embedding is set to print & preview or restricted, but it may be just a coincidence.

Environment: latest Xenko 1.9.3-beta, Windows 7 x64.

Steps to reproduce:
1. Download one of the following free fonts: [Crimson Text](https://www.fontsquirrel.com/fonts/crimson), [Carolinga](http://www.dafont.com/carolingia.font?fpp=100&l[]=10&l[]=1), [Maleficio](http://www.dafont.com/maleficio.font?fpp=100&psize=l&sort=date&l[]=10&l[]=1&back=theme).
2. Create a SpriteFont asset.
3. Either choose a system font as a source, or pick font file, does not matter.
4. Select Signed Distance Field as a font type.
5. Save SpriteFont.

Exception text: http://pastebin.com/bBvU2RH7
~~~~
Exception in command SpriteFontAsset: 01ae4cb4-284c-4a3b-9f61-84f4cd87abcf:
System.OutOfMemoryException: Out of memory.
   at System.Drawing.Image.FromFile(String filename, Boolean useEmbeddedColorManagement)
   at SiliconStudio.Xenko.Assets.SpriteFont.Compiler.SignedDistanceFieldFontImporter.LoadSDFBitmap(Char c, Int32 width, Int32 height, Int32 offsetx, Int32 offsety) in C:\TeamCity\work\80a49494ba341a6a\sources\engine\SiliconStudio.Xenko.Assets\SpriteFont\Compiler\SignedDistanceFieldFontImporter.cs:line 68
   at SiliconStudio.Xenko.Assets.SpriteFont.Compiler.SignedDistanceFieldFontImporter.ImportGlyph(FontFace fontFace, Char character, FontMetrics fontMetrics, Single fontSize) in C:\TeamCity\work\80a49494ba341a6a\sources\engine\SiliconStudio.Xenko.Assets\SpriteFont\Compiler\SignedDistanceFieldFontImporter.cs:line 212
   at SiliconStudio.Xenko.Assets.SpriteFont.Compiler.SignedDistanceFieldFontImporter.Import(SpriteFontAsset options, List`1 characters) in C:\TeamCity\work\80a49494ba341a6a\sources\engine\SiliconStudio.Xenko.Assets\SpriteFont\Compiler\SignedDistanceFieldFontImporter.cs:line 167
   at SiliconStudio.Xenko.Assets.SpriteFont.Compiler.SignedDistanceFieldFontCompiler.ImportFont(SpriteFontAsset options, Single& lineSpacing, Single& baseLine) in C:\TeamCity\work\80a49494ba341a6a\sources\engine\SiliconStudio.Xenko.Assets\SpriteFont\Compiler\SignedDistanceFieldFontCompiler.cs:line 139
   at SiliconStudio.Xenko.Assets.SpriteFont.Compiler.SignedDistanceFieldFontCompiler.Compile(IFontFactory fontFactory, SpriteFontAsset fontAsset) in C:\TeamCity\work\80a49494ba341a6a\sources\engine\SiliconStudio.Xenko.Assets\SpriteFont\Compiler\SignedDistanceFieldFontCompiler.cs:line 111 
   at SiliconStudio.Xenko.Assets.SpriteFont.SpriteFontAssetCompiler.SignedDistanceFieldFontCommand.DoCommandOverride(ICommandContext commandContext) in C:\TeamCity\work\80a49494ba341a6a\sources\engine\SiliconStudio.Xenko.Assets\SpriteFont\SpriteFontAssetCompiler.cs:line 167 
   at SiliconStudio.BuildEngine.Command.DoCommand(ICommandContext commandContext) in C:\TeamCity\work\80a49494ba341a6a\sources\common\buildengine\SiliconStudio.BuildEngine.Common\Command.cs:line 80
   at SiliconStudio.BuildEngine.CommandBuildStep.<StartCommand>d__21.MoveNext() in C:\TeamCity\work\80a49494ba341a6a\sources\common\buildengine\SiliconStudio.BuildEngine.Common\CommandBuildStep.cs:line 0
~~~~

**Comment by LautrecOfCarim** [comment] 2017-01-24 02:42
Thank you for the report, I'll investigate.

**Comment by LautrecOfCarim** [comment] 2017-02-03 05:05
Hi again,

I tested the fonts, but it didn't throw for me. Can you send me your PC's specs? Also, does it happen on a new project, or only in the game project you are working on, and does it happen consistently? It's possible that there was another issue or memleak which leads to this state, but I couldn't reproduce it.

**Comment by EnoughTea** [comment] 2017-02-03 08:45
Hi!
Exception does happen on both new and existing projects consistently.
[PC specs](http://pastebin.com/McCMLj3H):
```
CPU
    Intel Core i7 4770K @ 3.50GHz
    Haswell 22nm Technology
RAM
    8,00GB Single-Channel DDR3 @ 798MHz (10-10-10-27)
Motherboard
    Gigabyte Technology Co. Ltd. Z87-HD3 (SOCKET 0)
Graphics
    VP2365 SERIES (1920x1080@60Hz)
    2047MB NVIDIA GeForce GTX 670 (Gigabyte)
```

Since it turned out to be a tricky bug, I tried to do a bit of debugging on my end. If my findings are correct, exception happens due to `msdfgen` tool failure. It fails to generate a valid character bitmap for a specific symbol. Said symbol is different between fonts. 

Lets take Crimson Text font for example, it fails fast for me. Generating starts from the `!` value and then value is incremented by 1. So `!`, `"` and `#` bitmaps are generated correctly, it seems:
![!](http://i.imgur.com/BnpQnur.png)
!["](http://i.imgur.com/Wc5PRSS.png)
![#](http://i.imgur.com/LM2PJRO.png)
Now `$` comes, but bitmap generated for `$` turns out to be an empty file with 0 bytes length. Empty file counts as existing, so `SignedDistanceFieldFontImporter.LoadSDFBitmap` tries to load it via `Image.FromFile`, which fails, of course.

Now, why `msdfgen` is incapable of generating specific symbols from specific fonts on my PC, I do not know. Its issue https://github.com/Chlumsky/msdfgen/issues/24 looks related, and it is not closed yet.

**Comment by LautrecOfCarim** [comment] 2017-02-03 09:13
Thank you for investigating the problem. I confirmed that Crimson fails to display some of those characters. I'll try updating `msdfgen` and see if this fixes the issue.

It still doesn't crash for me, but I'll make `SignedDistanceFieldFontImporter.LoadSDFBitmap` more secure in case the conversion fails.

**Comment by LautrecOfCarim** [comment] 2017-02-06 06:52
I updated `msdfgen`, you can grab the .exe directly if you don't want to wait for the patch:
[msdfgen.zip](https://github.com/SiliconStudio/xenko/files/753799/msdfgen.zip)

Copy it to Xenko's install dir, Xenko.1.9.3-beta/Bin/Windows-Direct3D11/ and tell me if it works for you.

Most glyphs work but I'm still getting some visual glitches with certain fonts. `$` for Crimson-Italic looks broken, and the original tool has the same problem. I checked the decoding now uses `FT_Outline_Decompose()` which can mean it's a freetype problem.

**Comment by EnoughTea** [comment] 2017-02-06 10:46
Like you've said, updated `msdfgen` works for Crimson Text, in a sense that Xenko studio does not crash.

However, there is an interesting behaviour for Carolingia font at `^`(0x005E) symbol.
Using Xenko studio, `msdfgen` produces empty 0-length file, like before. Like before, studio crashes as a result. 
But when exported manually via cmd, `msdfgen` produces completely black bitmap without any error messages. What gives? :)

**Comment by EnoughTea** [comment] 2017-02-06 11:02
`FT_Outline_Decompose` is a familiar name, I remember it ruining my day few years ago, when I fiddled with SharpFont. It is easy to make an assumption that `FT_Outline_Decompose` walks through all the outline contour-points consecutively and performs a callback for every point. 

This is not the case, however, because TrueType allows on-curve spline points to be omitted under certain assumptions. Which means `FT_Outline_Decompose` can drop a pair of points in some symbols of some TrueType fonts and replace them with a single computed point. 

So if a FreeType user assumes the exact point correlation with a raw glyph data, then it will look like there is a gap in the outline: a consecutive sequence followed with sequences of skipping by one point or more. Omitting points is a rare occurence, so in case of a wrong assumption a bug can go unnoticed for a long time. 

Don't know if this is the case with `msdfgen`, just thought it may be a relevant experience.

**Comment by EnoughTea** [comment] 2017-02-06 11:38
Oh, it is much more simpler: Carolingia does not have a `^` glyph. I was sure it does. But still, it would be better not to crash in case of empty glyph.

**Comment by LautrecOfCarim** [comment] 2017-02-07 01:54
So the msdfgen.exe is just the latest tool update, but if it fails the Xenko game studio will still crash. If you don't want to wait for 1.9.4-beta and are building from source, use this patch:
[0001-Editor-Workaround-for-failed-msdfgen-glyph-generatio.zip](https://github.com/SiliconStudio/xenko/files/756335/0001-Editor-Workaround-for-failed-msdfgen-glyph-generatio.zip)

About overlapping contours, the original author confirmed they are not supported for now. I think msdfgen also supports .svg as input, but I haven't looked into it much. If it works well I can add the option to patch some glyphs with an .svg, but that will require a little bit more work.

**Comment by LautrecOfCarim** [comment] 2017-02-10 02:39
There was an update from Viktor Chlumský, and it seems to work, here is the new tool: [msdfgen.zip](https://github.com/SiliconStudio/xenko/files/765544/msdfgen.zip)

If it works for you, I can close this issue. Again, if there are empty glyphs you'll have to wait for 1.9.4-beta for the crash fix.

**Comment by EnoughTea** [comment] 2017-02-10 07:13
Well, editor crash is fixed, so `msdfgen` accuracy or its rendering in Xenko is a separate issue.
For me `!@#$*` are still most noticably distorted between fonts, so is every symbol in "fancy" fonts imitating handwriting/calligraphy. How French Scipt MT, bundled with MS Office, looks in Xenko:
![Warped French Script MT](http://i.imgur.com/8K7aiPd.png)
vs usual GDI:
![Proper French Script MT](http://i.imgur.com/e38mgJP.png)

**Comment by LautrecOfCarim** [comment] 2017-02-10 07:19
It seems the font size is too small to interpolate nicely, try setting the font size to 48 or 64.
Also, if your text doesn't animate or resize, consider using Runtime Rasterized fonts, they also support snapping.

**Comment by EnoughTea** [comment] 2017-02-10 07:34
Yes, setting font size to values >= 60 fixed it, thanks!

**Closed** 2017-02-10 07:46 UTC
Labels: bug
