### ISSUE TITLE
Please Help me in Xenko

### ISSUE THREAD

**Issue by JPMB123** [SiliconStudio/xenko#601] opened 2017-06-17 03:39 UTC
When i create a new project it always says Operation Cancelled here is the details:
```
Error: An exception occurred while generating the template.. Microsoft.Build.Exceptions.InvalidProjectFileException: The tools version "15.0" is unrecognized. Available tools versions are "2.0", "3.5", "4.0".  C:\Users\Admin\Documents\Xenko Projects\MyGame\MyGame\MyGame.Game\MyGame.Game.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Project.Data.InitializeForEvaluation(IToolsetProvider toolsetProvider)
   at Microsoft.Build.Evaluation.Evaluator`4..ctor(IEvaluatorData`4 data, ProjectRootElement projectRootElement, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at SiliconStudio.Assets.VSProjectHelper.LoadProject(String fullProjectLocation, String configuration, String platform, Dictionary`2 extraProperties) in C:\TeamCity\work\80a49494ba341a6a\sources\assets\SiliconStudio.Assets\VSProjectHelper.cs:line 200
   at SiliconStudio.Assets.Package.FindAssetsInProject(String projectFullPath, String& nameSpace) in C:\TeamCity\work\80a49494ba341a6a\sources\assets\SiliconStudio.Assets\Package.cs:line 1380
   at SiliconStudio.Assets.Package.FindAssetsInProject(ICollection`1 list, Package package) in C:\TeamCity\work\80a49494ba341a6a\sources\assets\SiliconStudio.Assets\Package.cs:line 1407
   at SiliconStudio.Assets.Package.ListAssetFiles(ILogger log, Package package, Boolean listAssetsInMsbuild, Nullable`1 cancelToken) in C:\TeamCity\work\80a49494ba341a6a\sources\assets\SiliconStudio.Assets\Package.cs:line 1374
   at SiliconStudio.Assets.Package.LoadTemporaryAssets(ILogger log, List`1 assetFiles, Nullable`1 cancelToken, Boolean listAssetsInMsbuild, Func`2 filterFunc) in C:\TeamCity\work\80a49494ba341a6a\sources\assets\SiliconStudio.Assets\Package.cs:line 967
   at SiliconStudio.Xenko.Assets.Presentation.Templates.NewGameTemplateGenerator.Generate(SessionTemplateGeneratorParameters parameters) in C:\TeamCity\work\80a49494ba341a6a\sources\editor\SiliconStudio.Xenko.Assets.Presentation\Templates\NewGameTemplateGenerator.cs:line 166
   at SiliconStudio.Assets.Editor.Components.TemplateDescriptions.SessionTemplateGenerator.Run(SessionTemplateGeneratorParameters parameters) in C:\TeamCity\work\80a49494ba341a6a\sources\editor\SiliconStudio.Assets.Editor\Components\TemplateDescriptions\SessionTemplateGenerator.cs:line 41
   at SiliconStudio.Assets.Editor.Components.TemplateDescriptions.TemplateGeneratorHelper.<>c__DisplayClass0_0`1.<RunTemplateGeneratorSafe>b__0() in C:\TeamCity\work\80a49494ba341a6a\sources\editor\SiliconStudio.Assets.Editor\Components\TemplateDescriptions\TemplateGeneratorHelper.cs:line 56
```

**Comment by dfkeenan** [comment] 2017-06-17 05:44
Might be the same problem as #598 / #583. Have a look at the "solution" in those.

**Comment by Kryptos-FR** [comment] 2017-06-17 06:58
Duplicate of #583 and #598.

**Closed by Kryptos-FR** 2017-06-17 06:58 UTC
